
let BASE_URL = "http://localhost:8081/";
let SIGNUP_API = BASE_URL + "signup";
let CREATE_EMPLOYEE_API = BASE_URL + "create";
let CATEGORIES_API = BASE_URL + "categories";
let EMPLOYEES_API = BASE_URL + "employees";
let UPDATE_EMPLOYEE_API = BASE_URL + "update";
let EMPLOYEE_BY_ID_API = BASE_URL + "employee/";
let DELETE_EMPLOYEE_API = BASE_URL + "delete/";


export {SIGNUP_API as SIGNUP_API, CATEGORIES_API as CATEGORIES_API, CREATE_EMPLOYEE_API as CREATE_EMPLOYEE_API, EMPLOYEES_API as EMPLOYEES_API, UPDATE_EMPLOYEE_API as UPDATE_EMPLOYEE_API, EMPLOYEE_BY_ID_API as EMPLOYEE_BY_ID_API, DELETE_EMPLOYEE_API as DELETE_EMPLOYEE_API};